name: Build Release Version
on:
  push:
    branches:
      - master

jobs:
  master:
    if: "startsWith(github.event.head_commit.message, 'Release version')"
    strategy:
      matrix:
        step: ['android', 'ios']
    name: ${{ matrix.step }}
    runs-on: mac-worker
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - name: ${{ matrix.step }}
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
        KS_PASSWORD: ${{ secrets.KS_PASSWORD }}
        NEXTCLOUD_CONFIG: ${{ secrets.NEXTCLOUD_CONFIG }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        node ./scripts/run-build.mjs --${{ matrix.step }} --release
